services:
  zenoh_router:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    network_mode: host
    ipc: host
    volumes:
      - ./config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5:/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
    environment:
        - RMW_IMPLEMENTATION=rmw_zenoh_cpp
        - ZENOH_ROUTER_CONFIG_URI=/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
    command: >
      ros2 run rmw_zenoh_cpp rmw_zenohd

  talker:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    network_mode: host
    ipc: host
    environment:
        - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    command: >
      ros2 run demo_nodes_cpp talker

  listener:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    network_mode: host
    ipc: host
    environment:
        - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    command: >
      ros2 run demo_nodes_cpp listener

