
x-common-config:
  &common-config
  network_mode: host
  ipc: host
  environment:
        - RMW_IMPLEMENTATION=rmw_zenoh_cpp

services:
  zenoh_router:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    <<:
      - *common-config
    volumes:
      - ./config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5:/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
      - ./config/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5:/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5
    environment:
        - ZENOH_ROUTER_CONFIG_URI=/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
        - ZENOH_SESSION_CONFIG_URI=/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5
    command: >
      ros2 run rmw_zenoh_cpp rmw_zenohd

  talker:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    <<:
      - *common-config
    command: >
      ros2 run demo_nodes_cpp talker

  listener:
    build:
        context: ./
        dockerfile: docker/Dockerfile
    <<:
      - *common-config
    command: >
      ros2 run demo_nodes_cpp listener

