name: build_docker

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./dockerfile/Dockerfile --tag wiktorbajor/rmw_zenoh_docker:rolling
    - name: Push image to dockerhub
      run: |
        docker login -u wiktorbajor -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push wiktorbajor/rmw_zenoh_docker:rolling
